title: Leap Day theme
description: Leap Day is a theme for GitHub Pages.
show_downloads: true
url: 'https://rsaavy.github.io/PythonCodeClub-TBS-SCT/https://rsaavy.github.io/PythonCodeClub-TBS-SCT/'
google_analytics:
theme: jekyll-theme-leap-day