theme: jekyll-theme-hacker
title: Python Code Club 
description: Python Code Club lunch time meet up at the Treasury Board  |  Déjeuner au Python Code Club au Secrétariat du Conseil du Trésor du Canada